### ISSUE TITLE
How to discover connection without using Intel XL710-QDA2 NICs

### ISSUE THREAD

**Issue by jiexray** [NetSys/resq#1]
Hello, 
I am trying to rebuild your system in my own server. However, I meet some confusing when I try to run the script `scripts/discover_connectivity.sh`.

The script is trying to find a file, and report the error message `find: ‘/sys/kernel/debug/i40e’: No such file or directory`. The whole running log is:
```
 sudo ./discover_connectivity.sh 172.16.1.86
root@172.16.1.86's password:
root@172.16.1.86's password:
root@172.16.1.86's password:
find: ‘/sys/kernel/debug/i40e’: No such file or directory
root@172.16.1.86's password:
find: ‘/sys/kernel/debug/i40e’: No such file or directory
root@172.16.1.86's password:

```

I find that the profile of my server is not Intel XL710-QDA2 NICs. Our server is using:

```
sudo ethtool -i ens3
driver: e1000
version: 7.3.21-k8-NAPI
firmware-version:
expansion-rom-version:
bus-info: 0000:00:03.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no
```

Could you share some idea on my problem? Thank you for your time.

Best wishes.

**Comment by tootoonchian** [comment]
Sorry, I missed this issue earlier. Line 25 of the script filters out the BDFs of devices of interest. You can adjust it to match your setup (e.g., hard code the BDFs or add your device to the grep regex).

Alternatively, if your only have a few links, you may manually populate `config/ports.toml` by following the format you see in `scripts/discover_connectivity.sh`.
